### PR TITLE
Feature/update 500 page in cloudflare

### PR DESCRIPTION
**Pull request by mr-nick17**
### What
- Updating html in [error page served by cloudflare](https://trello.com/c/gprvFjq5/1930-update-500-page-in-cloudflare)
- Reformatted ⬆️ so hopefully easier to read
- Updated/fixed formatting errors in readme

### How to review
Pull this branch and open the html in a browser
e.g.
```bash
file:///Users/{USERNAME}/src/github.com/ONSdigital/cdn.ons.gov.uk-assets/assets/html/error-pages/service-error.html
```
Check everything looks good 👍 
Check html is valid 👍 
Check the links work 👍 

### Who can review

Frontend dev

### CODE REVIEW

**Comment by lindenmckenzie** [comment]
Seems fine - no min height though?

**Review by lindenmckenzie — COMMENTED** [review]
Seems fine but no min height on the white block?

**Comment by mr-nick17** [comment]
> Seems fine but no min height on the white block?

Moving the `<footer>` outside of the "page content" `<div>` solves this

**Review by lindenmckenzie — APPROVED** [review]
Certainly better - not quite as much whitespace as in Paul's design but I'll approve :)

**Pull request merged**
